name: Linting & Formatting

on:
  push:
    branches: [main, dev]
  pull_request:

concurrency: 
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@master
        with:
          luaVersion: "luajit-2.1.0-beta3"

      - uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Install linter
        run: luarocks install luacheck

      - name: Lint
        run: luacheck lua

      - uses: JohnnyMorganz/stylua-action@v3
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         version: v0.20.0 # NOTE: we recommend pinning to a specific version in case of formatting changes
         # CLI arguments
         args: --check lua
