name: web_docs

on:
  push:
    branches:
      - master
    paths:
      - docs/**

jobs:
  web_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push docs to nvim-orgmode.github.io repository
        uses: nkoppel/push-files-to-another-repository@v1.1.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          source-files: 'docs/'
          destination-username: 'nvim-orgmode'
          destination-repository: 'nvim-orgmode.github.io'
          destination-branch: 'main'
          commit-email: 'github-actions@github.com'
