name: Push to Luarocks

on:
  push:
    tags:
      - '*'
  release:
    types:
      - created
  pull_request: # Runs test install without uploading
  workflow_dispatch: # Allows to trigger manually

jobs:
  luarocks-upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to count the commits
      - name: Get Version
        run: echo "LUAROCKS_VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-stable

      - run: |
          nix profile install nixpkgs#libgit2
          export GIT2_PATH=/nix/store/$(ls /nix/store | grep libgit2-20*)
          echo "GIT2_DIR=$GIT2_PATH" >> $GITHUB_ENV

      - name: LuaRocks Upload
        uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
        with:
          version: ${{ env.LUAROCKS_VERSION }}
          template: .github/workflows/rockspec.template
          test_interpreters: |
            neovim-stable
            neovim-nightly
          extra_luarocks_args: |
            GIT2_DIR=$GIT2_DIR
