name: panvimdoc

on:
  push:
    paths:
      - 'README.md'

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: pets.nvim
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs(help): auto generate docs"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
