name: release-please

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - lua_ls-typecheck
      - stylua
    types:
      - complete

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: pathlib.nvim
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          extra-files: |
            conf.py
